### ISSUE TITLE
Chef 12.4.1-1 on Solaris - Setting members directly is not supported by #<Chef::Provider::Group::Usermod:0x1989ca8>

### ISSUE THREAD

**Issue by dzabel** [chef-cookbooks/users#106]
Not sure how is responsible for this.

Also reported an issue here:
https://github.com/chef/chef/issues/3780

works using chef-12.4.0

**Comment by dzabel** [comment]
Stacktrace here: https://github.com/chef/chef/issues/3780

**Comment by jblaine** [comment]
Solaris is not listed as a supported OS in the README.md.

**Comment by dzabel** [comment]
@jblaine i know, but worked before. maybe someone is interested in.

**Comment by tas50** [comment]
This is actually a bug in the underlying chef user provider with Solaris.  I'm going to close out this bug since the chef/chef bug is tracking the issue.
