### ISSUE TITLE
Multiline ssh keys

### ISSUE THREAD

**Issue by adecarolis** [chef-cookbooks/users#128]
1.7.0 allowed multiline ssh keys using JSON arrays:
```
 $ cat cookbooks/users/templates/default/private_key.erb
<% Array(@private_key).each do |key| %>
<%= key %>
<% end -%>
```

On the other hand, 2.0.1 is simply putting out the JSON string:
```
 $ cat cookbooks/users/templates/default/private_key.erb
<%= @private_key %>
```
This applies to both `private_key.erb` and `public_key.erb`, but not to `authorized_keys.erb`. It breaks backwards compatibility and makes it difficult to create multiline keys.

How is one supposed to do this in 2.0.1?

Thanks

**Comment by iennae** [comment]
I checked the template in https://github.com/chef-cookbooks/users/releases/tag/v1.7.0, and it looks like the template hasn't changed. Is this perhaps something that was modified locally? I notice that https://github.com/chef-cookbooks/users/blob/master/templates/default/authorized_keys.erb totally has that style of template.

**Comment by adecarolis** [comment]
The file you linked is the one that hasn't changed, and that's ok.

The ones that changed are:
https://github.com/chef-cookbooks/users/blob/master/templates/default/private_key.erb
https://github.com/chef-cookbooks/users/blob/master/templates/default/public_key.pub.erb

As you see they both have a single line, no array iteration. That's the problem I'm talking about.

**Comment by adecarolis** [comment]
I double checked. You are right... my local 1.7.0 had been modified. Thank you for pointing this out.

**Comment by iennae** [comment]
Well if it's a feature that is helpful, would be great to know :) It sounds like it's useful, just wanted to make sure I understood the change.

**Comment by adecarolis** [comment]
Well, I believe it is useful. In facts I was about to override those templates in a wrapper cookbook.
My problem is that we use private keys that are multiline. JSON, oh the other hand, does not allow multiline strings. The template you currently have in [authorized_keys.erb](https://github.com/chef-cookbooks/users/blob/master/templates/default/authorized_keys.erb does) solves the multiline problem applying [this](https://gun.io/blog/multi-line-strings-in-json) pattern. I need exactly the same thing for the other two files.
