### ISSUE TITLE
Removing a user does not work

### ISSUE THREAD

**Issue by davidmontgom** [chef-cookbooks/users#336]
Removing a user with "action": "remove", and rerunning the recipe does not remove a user.
This make using the cookbook not usable and dangerous .  Any reason why code fails to remove a user?  I can still ssh into a server, user is still there.
### Cookbook version

2.0.3
### Chef-client version

Chef: 12.12.15
### Platform Details

ubuntu 14.04
### Scenario:

Trying to remove a user

**Comment by nkadel-skyhook** [comment]
Was the user logged in at the time? This would have presented an error message to chef, since the "userdel" command will not flush an active user.

**Comment by jcii** [comment]
I'm seeing this as well. Within kitchen, we've created data bag stubs for two users. If I set the action to `create`, the kitchen run completes. If I subsequently change the action to `remove` on the same user, it fails. I verified that the user is in /etc/passwd and is not logged in.

Here's the databag we're using in kitchen:
```
{
  "id": "removeme",
  "uid": 50001,
  "comment": "",
  "shell": "/bin/false",
  "groups": [
    "sftponly"
  ],
  "home": "/site/pubchroot/home/removeme",
  "password": "0",
  "action": "create",
  "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAt6Ewr6+pxvhMjzb1D3mB5DAb8XGlFf6EAuQKFh+Qa2H4nbdCXSVSxMvk8E6HZC9YkcxsX9a/yTEhBQq5KClTEkP4A+FXnQz85mmq75t8a9+AggdeCArWWgF8tUXow08iTWnRn7SqX8f3y7DqOHEV1YZWhnp7mllFtkw7zcAqQqN6SMT6YvO2VITiDDO59MJF9Ri2rnIVUQkCmHUrXHcV1POn/tjU5b6iPKeNEo3EJN7vvtyEec9vcDmJ1XbaRVjxDUc4QnYhEFJSQDJfPTdYdzyr2WFLA/ksxNhZ8jUReZM0kdQf/GENICDBffjNUKjlnMOOBmzxqx91h6rORfz3uQ== jcarter@bumper.sea"
}
```

**Comment by adecarolis** [comment]
+1
(Centos 6.6)

**Comment by tas50** [comment]
I'm not able to reproduce this in the 5.0 release. I've also added a test to ensure we can remove a user, which is doing the right thing. If you're still seeing this issue with the 5.0 release please feel free to open this issue back up.
