### ISSUE TITLE
Can't destroy and create the guest machine 

### ISSUE THREAD

**Issue by idirocco** [chef-cookbooks/users#351]
### Cookbook version

2.0.0
### Chef-client version

12.5.1
### Platform Details

MacBook Pro early 2011. OSX El Capitan 10.11.4.

```
$ vagrant box list
opscode-ubuntu-12.04-i386 (virtualbox, 0)
ubuntu/trusty64           (virtualbox, 20150911.0.0)
```
### Scenario:

Trying to destroy and re-create the vm.
### Steps to Reproduce:

`vagrant destroy -f && vagrant up`
### Expected Result:

I expect the vm running.
### Actual Result:

[gist result](https://gist.github.com/idirocco/1ee765437cd725c31dfb96a0ef5b974c)

**Comment by iennae** [comment]
@idirocco This looks like a somewhat old version of the cookbook. Can you try a current version of the cookbook and see if you are still seeing issues? Please reopen if you are still having problems with the current version of the cookbook.
