### ISSUE TITLE
Deprecated features used! 

### ISSUE THREAD

**Issue by vskubriev** [chef-cookbooks/users#380]
### Cookbook version

users             4.0.1
### Chef-client version

Chef-client: 12.13.37 (are the same on all tested nodes)
### Platform Details

ubuntu 12.04, 14.04, 16.04 on baremetal
### Scenario:

I want to run cookbook without warnings. But I can't create a patch manually.
### Steps to Reproduce:

Create a databag for sysadmin user like:

```
me@xxx[~/chef-repo/data_bags/users][0] $ cat sysadmin.json 
{
  "id": "sysadmin",
  "ssh_keys": [
    "ssh-rsa AKEY== skubriev@domain.com"
  ],
  "groups": [ "root", "sysadmin" ],
  "action": "create",
  "password": "!!",
  "shell": "\/bin\/bash",
  "comment": "Server Admin",
  "nagios": {
    "email": "sysadmin@int.domain.com"
  }
}

```

include recipe `recipe[users::sysadmins]` of this cookbook in the runlist.
### Expected Result:

I want run chef-client without warnings in chef 12.
### Actual Result:

```
  Cloning resource attributes for group[sysadmin] from prior resource (CHEF-3694)
Previous group[sysadmin]: /var/chef/cache/cookbooks/users/providers/manage.rb:76:in `block (2 levels) in class_from_file'
Current  group[sysadmin]: /var/chef/cache/cookbooks/users/providers/manage.rb:154:in `block in class_from_file' at 1 location:
    - /var/chef/cache/cookbooks/users/providers/manage.rb:154:in `block in class_from_file'
```

**Comment by tas50** [comment]
This is resolved on master
