### ISSUE TITLE
users not removed from groups after updating data bag

### ISSUE THREAD

**Issue by Raboo** [chef-cookbooks/users#402]
### Cookbook version
5.0.0

### Chef-client version
12.19.36

### Platform Details
Ubuntu  16.04

### Scenario:
I'm creating a user and group called deploy from users_system data bag.
```
users_manage 'deploy' do
  group_id 2210
  action [:create]
  data_bag 'users_system'
end
```

Then I create ops users from data bag users_ops.
```
users_manage 'ops' do
  group_id 2330
  action [:create]
  data_bag 'users_ops'
end
```

Then I create dev users from data bag users_dev
```
users_manage 'dev' do
  group_id 2340
  action [:create]
  data_bag 'users_dev'
end
```

ops users used to have `"groups": [ "users", "admin", "sudo", "adm", "deploy", "ops" ]`.
Now ops have `"groups": [ "users", "admin", "sudo", "adm", "ops" ]`
dev have  `"groups": [ "users", "admin", "sudo", "adm", "deploy", "ops" ]`.

But ops users are not removed from the deploy group, bug, feature or misuse?

### Steps to Reproduce:
re-run chef-client.

### Expected Result:
I expected to that ops users would have been removed from deploy group.

### Actual Result:
ops users are not removed from deploy group.

**Comment by iennae** [comment]
The cookbook is working as expected based on what you've asked for it to do based on your description. The resource does not have a defined excluded members attribute so doesn't manage deleting users from groups. We may be missing some information here so reopen if you have additional information about this.

**Comment by Raboo** [comment]
Sorry, was my bad, I had same user in two different data bags.

**Comment by iennae** [comment]
Thanks for the update.
