### ISSUE TITLE
set manage_home to false

### ISSUE THREAD

**Issue by Raboo** [chef-cookbooks/users#403]
Is there a way to have manage_home set to false?
I don't want created users to get a copy of /etc/skel

**Comment by iennae** [comment]
Right now, the recipe as is does not parse a manage_home attribute within the databag. It does look to see if the [home directory is set](https://github.com/chef-cookbooks/users/blob/master/resources/manage.rb#L53) which if set to "/dev/null" will set manage_home to false. This probably isn't sufficient for your needs, but let us know.

**Comment by Raboo** [comment]
I also noticed that I need to create the user home directory when manage_home is set to false.
But I've tried different ways to get+set users primary group as owner for the users home folder. But it always fails cause the resource is evaluated at the start of the chef run before the user is created.

Does anyway have a smart way to exclude some resources from being evaluated before they actually are executed?

**Comment by Raboo** [comment]
So I added a PR, can someone help with the whole gid ownership thing?

**Comment by iennae** [comment]
When manage_home is set to false it means that you don't want chef to set up the directory as per the [user resource documentation](https://docs.chef.io/resource_user.html). 

It sounds like you are looking for [lazy evaluation of attributes](https://docs.chef.io/resource_common.html#lazy-evaluation) .

**Comment by Raboo** [comment]
Yes, that worked, will update the PR

**Comment by Raboo** [comment]
Ok, Lazy Evaluation added and README fixed. PR updated.

**Comment by Raboo** [comment]
Ok I feel I'm done with the "code" part. But some tests are failing, but I'll write about that in the PR.

**Comment by Raboo** [comment]
closing this issue as because it's become stale.
