### ISSUE TITLE
LWRP should operate on user and not group name 

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/users#56]
What is the reason for the LWRP to operate on a group name and not individual users?

**Comment by trekr5** [comment]
I've found that when I use this cookbook to ensure that only users from a databag on the Chef server get deployed to a particular machine, that if I create a user on the said machine independently of the data bag and add it to the group that i use the users_manage resource for, that the user is removed from the group but not from the machine. 

Is this correct behaviour for the users_manage resource?
