### ISSUE TITLE
ssh_keys only work if gid is provided

### ISSUE THREAD

**Issue by gimler** [chef-cookbooks/users#64]
I get the following error.

```
[31mError executing action `create` on resource 'users_manage[sysadmin]'[0m
================================================================================[0m
[0m
Chef::Exceptions::GroupIDNotFound[0m
---------------------------------[0m
template[/home/jenkins/.ssh/authorized_keys] (/var/lib/monsoon/repos/eventticketing/jenkins/chef/cookbooks/users/providers/manage.rb line 121) had an error: Chef::Exceptions::GroupIDNotFound: cannot determine group id for 'jenkins', does the group exist on this system?[0m
[0m
```

with the following user

```
{
  "id": "jenkins",
  "ssh_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAAD...",
  "groups": ["sysadmin", "users"],
  "shell": "\/bin\/bash"
}
```

if i provide a `gid` it works. I think the problem is that the create only the group if the gid is provided.
See https://github.com/sethvargo-cookbooks/users/blob/master/providers/manage.rb#L86

Can we rewrite it to create the group every time and only use the gid if provided?

**Comment by rtrauntvein** [comment]
+1

**Comment by gsaslis** [comment]
Just curious here: 
@rtrauntvein, @gimler - what platform were you guys working on?

**Comment by rtrauntvein** [comment]
I ran into the issue on SLES 11 SP3 here

Ubuntu worked fine

**Comment by gsaslis** [comment]
ok - makes sense.. Thanks! 
At least I know the SUSE-specific PR is not as bad now  :D

**Comment by tas50** [comment]
Looks like this was fixed on master. Feel free to open it back up if I'm mistaken.
