### ISSUE TITLE
Readme file - instruction on how to create a user has been deleted

### ISSUE THREAD

**Issue by ianbamforth** [chef-cookbooks/users#75]

**Comment by iennae** [comment]
Hi,

Apologies for the length in time getting back to this request. Is https://github.com/chef-cookbooks/users/blob/master/README.md not sufficient in creating a user?

Thank you!

Jennifer

**Comment by iennae** [comment]
I've updated the README now as well to hopefully clarify the issue. Please let me know if the update works for you.

Thanks!
