### ISSUE TITLE
Removing a User

### ISSUE THREAD

**Issue by elmic11111** [chef-cookbooks/users#79]
I added action remove to a user who has left. After uploading the databag I manually ran chef client on one of my servers since I never removed a user before. It gave me the following error:

```
* user[bobb] action remove (up to date)
* directory[/home/bobb/.ssh] action create
  * Parent directory /home/bobb does not exist, cannot create /home/bobb/.ssh
  ================================================================================
  Error executing action `create` on resource 'directory[/home/bobb/.ssh]'
  ================================================================================

  Chef::Exceptions::EnclosingDirectoryDoesNotExist
  ------------------------------------------------
  Parent directory /home/bobb does not exist, cannot create /home/bobb/.ssh

  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/users/providers/manage.rb

  113:          directory "#{home_dir}/.ssh" do
  114:            owner u['username']
  115:            group u['gid'] || u['username']
  116:            mode "0700"
  117:        end
  118:      end

  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/users/providers/manage.rb:113:in `block (3 levels) in class_from_file'

  directory("/home/bobb/.ssh") do
    provider Chef::Provider::Directory
    action :create
    retries 0
    retry_delay 2
    guard_interpreter :default
    path "/home/bobb/.ssh"
    cookbook_name "aws_users"
    mode "0700"
    owner "bobb"
    group "bobb"
```

I'm not sure why it's trying to create it after it's removed it. 

In my cookbook I have 

node['authorization']['adtional_groups'].each do |group|
    users_manage group do
        action [ :create, :remove ]
    end
end

include_recipe "sudo"

**Comment by elmic11111** [comment]
I'm not sure, but I think part of the problem might be that they are in more then one group. But figured I mention it. 

Also, I tried changing the action to lock and got:

      * user[bobb] action lock
      * Cannot modify user bobb - does not exist!
      ================================================================================
      Error executing action `lock` on resource 'user[bobb]'
      ================================================================================

      Chef::Exceptions::User
      ----------------------
      Cannot modify user bobb - does not exist!

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/users/providers/manage.rb

       94:       user u['username'] do
       95:         uid u['uid']
       96:         if u['gid']
       97:           gid u['gid']
       98:         end
       99:         shell u['shell']

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/users/providers/manage.rb:94:in `block (2 levels) in class_from_file'

      user("bobb") do
        action [:lock]
        supports {:manage_home=>true}
        retries 0
        retry_delay 2
        guard_interpreter :default
        username "bobb"
        comment "Gopal, Naveenkumar - Naveenkumar.Gopal@am.sony.com"
        home "/home/bobb"
        iterations 27855
        cookbook_name "aws_users"
      end

**Comment by nkadel-skyhook** [comment]
The whole "I insist on creating a .ssh directory, even if you didn't set any SSH attributes" is problematic.: I've already submitted a patch for just that issue.

**Comment by tas50** [comment]
I've created a test for the removal of a user that exists and the removal of a user that no longer exists on the system. Both of these scenarios are working in the 5.0 cookbook. I'm going to close this issue out unless there's something I'm missing
