### ISSUE TITLE
Possible to manage groups for existing users

### ISSUE THREAD

**Issue by Rockstar04** [chef-cookbooks/users#95]
Is there any way for the lwrp to support adding new groups to users that have already been created.

Currently the group would only be added if I provision a new box, or create a new user.

**Comment by bshaw** [comment]
I'm looking for something similar too. I've got a fleet of AWS instances of varying Linux variants, on creation some get a default user 'ec2-user' and some get 'ubuntu' and I'd like to keep those account around.

If I understand correctly, the manage action should take care of this by adding the user to the appropriate group if the user exists, but it doesn't seem to be supported in this cookbook even though the doc says, "You can pass any action listed in the user resource for Chef via the "action" option." Maybe I'm just missing something though.

**Comment by FlorentFlament** [comment]
From what I could experience, users_manage LWRP did not add the users to the groups specified in the data bag. I propose this feature in the following pull request:
https://github.com/opscode-cookbooks/users/pull/107

**Comment by jloomb** [comment]
+1 the README.md#L98 incorrectly states "action: String Supported actions are one's supported by the user resource...." but only actually allows nothing, create, remove. Cant lock, unlock, manage or modify :(

**Comment by iennae** [comment]
Thank you @FlorentFlament for your contribution. This has been merged into v2.0.3 of the cookbook. Can folks please confirm that this works for your purposes?

@jloomb can you open a separate issue for the supported actions issue? That's not the same as adding users to groups for existing users.
